import Head from 'next/head'
import Image from 'next/image'
import Graph from '../components/graph'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{height: '100vh', background: '#181925'}}>
        <Graph />
      </main>
    </div>
  )
}
